In [ ]:
import numpy as np

In [ ]:
!git clone https://github.com/yoonchaiyoung/DeepLearning.git

## 파이썬의 list와 numpy의 ndarray의 차이점

- 파이썬의 list보다 속도가 훨씬 빠름
- 파이썬의 list보다 배열을 훨씬 쉽게 다룰 수 있음



- 파이썬의 list : 모든 것 담을 수 있음(객체 등)
- ndarray : 숫자만 담을 수 있음

In [ ]:
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
# 2차원 배열 만들기 with Python의 list

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
type(arr2)

numpy.ndarray

# 1차원 배열
## np.arange

In [ ]:
arr = np.arange(10)  # 0 ~ 10까지 들어있는 숫자 배열
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(1, 10)  # 1 ~ 9까지 들어있는 숫자 배열
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(1, 10, 2)  # 1 ~ 9까지 2씩 띄워 가면서
arr

array([1, 3, 5, 7, 9])

## 다차원 배열
- np.zeros
- np.ones
- np.full

## np.zeros
지정한 차원에 모든 원소를 0으로 채운다.

In [ ]:
np.zeros(5)  # 1차원 배열에 5개의 0을 채운다.

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((4, 5))  # 2차원 배열(4행 5열)에 0을 채운다.

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((3, 4, 5))  # 3차원 배열에 0을 채운다.

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

## np.ones
지정한 차원에 모든 원소를 1로 채운다.

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((3, 4, 5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
np.ones((2, 3)) * 5  # 5로 채우고 싶을 때

array([[5., 5., 5.],
       [5., 5., 5.]])

## np.full
지정한 차원의 배열에 원하는 수를 채워 넣는다.

In [ ]:
np.full((3, 4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

## 단위 행렬 만들기
- np.eye

In [ ]:
np.eye(3)  # 대각선이 1, 나머지 0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, 4)  # 정방행렬만 되는 것 아님

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# 구간 나누기
- np.linspace

In [ ]:
np.linspace(1, 10, 3)  # 1~10까지 3개의 구간 만들기

array([ 1. ,  5.5, 10. ])

In [ ]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

# Random을 사용하기 위한 numpy
- 보통 랜덤한 배열은 딥러닝에서 매개변수의 초기화를 하기 위해 사용
- 딥러닝에서는 일반적으로  Xavier 초깃값, He 초깃값, 정규분포 초깃값을 계산

In [ ]:
# 일반적인 랜덤값 만들기(균등분포 x, 정규분포 x)
np.random.rand(2, 3)  # 0 ~ 1 사이의 랜덤값 만들기, 2*3 행렬

array([[0.27509115, 0.84167628, 0.73357632],
       [0.51127612, 0.01571344, 0.34896184]])

In [ ]:
# 정규분포 랜덤값 만들기
np.random.randn(10)

array([ 0.84695273,  1.24330788,  0.49142257,  0.00794542, -1.69838599,
       -0.3172582 ,  1.86058142, -0.23629437, -0.93047269, -0.48258444])

In [ ]:
np.random.randn(3, 4, 2)

array([[[-1.01775639,  2.02881394],
        [-0.4337625 , -1.3248448 ],
        [-1.55003832, -0.31696199],
        [ 0.59238646, -1.39256131]],

       [[-0.18371422, -0.94929436],
        [-0.64328838, -1.35646753],
        [ 0.84606584, -0.7920338 ],
        [-0.51572415, -0.05229638]],

       [[ 1.51037212,  0.30554554],
        [-0.12105296, -0.25520542],
        [-0.03688979,  0.20518948],
        [ 1.26713303, -0.76399121]]])

In [ ]:
# 균등분포 랜덤값 만들기
np.random.uniform(1.0, 3.0, size=(4, 5))  #  size로 배열의 형상(shape) 지정

array([[2.8952138 , 2.11062432, 1.42784246, 2.84038059, 1.10619822],
       [2.12666144, 2.19897209, 1.38047154, 1.17476723, 2.93256152],
       [2.92493813, 1.26983173, 1.20135709, 2.68590305, 2.0590961 ],
       [2.07509347, 2.39804062, 2.57071925, 1.89066413, 1.14605373]])

# 정수 랜덤 만들기

In [ ]:
np.random.randint(1, 100, size=(5))  # 1~100까지 중 5개 랜덤하게

array([42, 83, 30, 86, 30])

In [ ]:
np.random.randint(1, 100, size=(5, 1))

array([[ 8],
       [25],
       [68],
       [99],
       [73]])

In [ ]:
np.random.randint(1, 100, size=(3, 4, 5))

array([[[28, 65, 77, 41, 96],
        [89, 50, 62, 32, 42],
        [82, 39, 71, 47, 81],
        [81, 15, 22, 24, 80]],

       [[72,  7, 90, 27, 56],
        [19,  5, 80, 25, 16],
        [96, 99, 83, 20, 79],
        [52, 68, 30, 27, 48]],

       [[26, 34, 84,  9, 54],
        [94, 58, 49, 87, 80],
        [79,  2, 96, 33, 28],
        [93, 21, 56, 67, 26]]])

In [ ]:
# 1차원 배열에서 랜덤 샘플링하기(중복 X)
# 미니배치를 만들 때 사용된다.
np.random.choice(100, size=(3, 4))

array([[83, 30, 92, 55],
       [93, 17, 48, 77],
       [54, 51, 15, 92]])

In [ ]:
arr = np.arange(1, 6)  # 1~5 사이의 숫자가 순서대로 들어있음
np.random.choice(arr, size=(2, 2), replace=True)  # Ture면 원소를 중복 추출O, False면 중복 추출 X

array([[1, 2],
       [5, 2]])

# 인덱스와 슬라이싱

In [ ]:
arr = np.arange(1, 11).reshape(2, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
# arr["바깥에 있는 데이터"].... 데이터에 가까워지고 있음....[]
arr[0][2]

3

In [ ]:
arr[0, 2]

3

In [ ]:
arr[:, 2]  # 행, 열로 보지말기.
# 데이터가 추가되는 방향으로 보기.
# 4차원 이상의 데이터를 다룰 때 행, 열방향을 생각할 수 없음

array([3, 8])

In [ ]:
# 3차원 배열 : Tensor
arr = np.arange(36).reshape(3, 4, 3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [ ]:
arr[:, :2, :2]

array([[[ 0,  1],
        [ 3,  4]],

       [[12, 13],
        [15, 16]],

       [[24, 25],
        [27, 28]]])

In [ ]:
arr[:2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

# 배열의 차원과 형상
- 형상(shape)
- 차원수(ndim)

In [ ]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr.shape  # 머신러닝, 딥러닝을 할 때 항상보기!

(3, 4)

In [ ]:
arr.ndim

2

# 차원수 늘리기
- 이미지 분석(CNN) 레이어를 사용하기 위해서는 필수적으로 알아야 한다.

In [ ]:
# Tensorflow 기준으로 CNN에 사용되어지는 배열의 형상은 항상 다음과 같다.
arr2 = arr[np.newaxis, :, :, np.newaxis]
arr2.shape
# 출력값 : (1, 3, 4, 1) : (이미지 갯수, 가로 갯수, 세로 갯수, 채널의 수)

(1, 3, 4, 1)

In [ ]:
arr2.ndim

4

In [ ]:
arr2

array([[[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]],

        [[ 8],
         [ 9],
         [10],
         [11]]]])

In [ ]:
arr3 = np.squeeze(arr2)  # 1로 되어있는 차원의 데이터를 삭제해줌
                         # reshape을 이용해도 똑같은 일 할 수 있음
arr3.shape

(3, 4)

In [ ]:
arr4 = arr[np.newaxis, ..., np.newaxis]  #  원래 있던 데이터를 가져오겠다
# ... : 원래 데이터 처음부터 끝까지 가져오겠다는 이유
# arr이 가지고 있던 차원에
# 앞뒤로 새로운 차원 추가하는 것

# ...이 아닌 [np.newaxis, :, :, np.newaxis]가 좀 더 명확하게 보이기는 함
arr4.shape

(1, 3, 4, 1)

# 배열의 형상(shape) 바꾸기
- np.newaxis를 활용해서 축을 추가한다. (차원수를 늘릴 때 활용)

## 평탄화
- ravel()
- flatten()

## 형상 변환
- reshape()

In [ ]:
x = np.arange(15).reshape(3, 5)
x.shape

(3, 5)

In [ ]:
# ravel : 평탄화 시킨 참조 배열을 만들어 낸다. (View 또는 Reference)
# flatten : 평탄화 시킨 복사 배열을 만들어 낸다. (복사본)

temp = np.ravel(x)  # x : 3*5 행렬이었음
print(temp)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
temp[0] = 100
print(x)
# ravel시킨 객체를 변경시키면 원본 객체가 변경됨
# 참조.

[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


In [ ]:
y = np.arange(15).reshape(3, 5)

In [ ]:
temp2 = y.flatten()  # y를 1차원으로 쭉 펴낸 배열을 새롭게 만들어 낸다.
# 새롭게!!
print(temp2)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
temp2[0] = 100
print(temp2)
print(y)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
# reshape (배열의 형상을 바꾸기)
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
x.reshape(2, 5, 2)  # 2 * 5 * 2 = 20
# 곱은 항상 전체가 되어야 함

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [ ]:
x.reshape(2, 2, -1)  # -1(조커) : 다 채우고 나머질 채우겠다.
# -1을 2개 사용 불가 -> 채울 방법이 없음

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [ ]:
# x.reshape(3, -1)  # 갯수의 곱 = 전체 인데, 3은 20의 약수가 아님

In [ ]:
x.reshape(-1, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
x.reshape(-1, 5).shape

(4, 5)

In [ ]:
x.reshape(2, -1, 5).shape

(2, 2, 5)

# 브로드 캐스팅
- 차원수가 다른 배열끼리의 연산

In [ ]:
x = np.arange(15).reshape(3, 5)
y = np.random.randn(15).reshape(3, 5)

print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[-0.63541897  0.73711763  1.64332694  1.02843857  1.37879975]
 [ 1.37802886 -0.76607335  0.0542691   1.78009338 -0.06967895]
 [ 0.65880528  0.0819691  -0.01549393  0.43496536 -1.50741074]]


In [ ]:
x * y  # 원소의 곱

array([[ -0.        ,   0.73711763,   3.28665389,   3.08531571,
          5.51519901],
       [  6.8901443 ,  -4.59644008,   0.37988372,  14.24074702,
         -0.62711056],
       [  6.58805276,   0.90166011,  -0.18592721,   5.6545497 ,
        -21.10375031]])

In [ ]:
x * 3  # 배열 * 스칼라값
# 스칼라값이 브로드 캐스팅된다.
# 모든 원소에 3이 곱해지는 것이 아닌, 스칼라값이 3*4의 형태로 바뀌는 것

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42]])

In [ ]:
a = np.arange(12).reshape(4, 3)  # (4, 3)
b = np.arange(100, 103)  # (3,)  # 1차원 배열
c = np.arange(1000, 1004)  # (4,)  # 1차원 배열
d = b.reshape(1, 3)  # (1, 3)

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

(4, 3)
(3,)
(4,)
(1, 3)


In [ ]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [ ]:
a + c
# a의 가로는 3개
# c의 가로는 4개라서
# 브로드캐스팅 불가

ValueError: ignored

In [ ]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

# 전치행렬 만들기
- 행 <-> 열
- 행렬의 역전파 때 나옴

In [ ]:
e = np.arange(6).reshape(2, 3)
e

array([[0, 1, 2],
       [3, 4, 5]])