In [1]:
import numpy as np

In [2]:
A = np.array([1, 2, 3, 4])  # 행렬은 주로 대문자로 표현
B = np.arange(1, 7).reshape(3, 2)

In [3]:
A

array([1, 2, 3, 4])

In [4]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
A.shape

(4,)

In [6]:
B.shape

(3, 2)

In [7]:
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(1, 7).reshape(3, 2)

In [8]:
A.shape

(2, 3)

In [9]:
B.shape

(3, 2)

A와 B의 내적을 구할 수 있나요?

Yes

In [10]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

B와 A의 내적을 구할 수 있나요?

Yes

In [11]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [12]:
C = np.arange(1, 5).reshape(2, 2)

In [13]:
C.shape

(2, 2)

A와 C의 내적을 구할 수 있나요?

No

In [14]:
A.shape

(2, 3)

In [15]:
C.shape

(2, 2)

In [16]:
np.dot(A, C)

ValueError: ignored

C와 A의 내적을 구할 수 있나요?

Yes

In [17]:
np.dot(C, A)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [18]:
D = np.arange(1, 3)
D

array([1, 2])

In [19]:
D.shape  # 1차원

(2,)

A와 D의 내적 구할 수 있나요?

No

In [20]:
A.shape, D.shape

((2, 3), (2,))

In [21]:
np.dot(A, D)

ValueError: ignored

D와 A의 내적 구할 수 있나요?

Yes

In [22]:
np.dot(D, A)

array([ 9, 12, 15])

In [23]:
# 차원의 수는 달라도 행렬의 곱 가능
# shape의 이어지는 숫자만 같으면 됨

# 신경망

In [24]:
X = np.array([1.0, 0.5])  # 입력값 2개
W1 = np.array([
               [0.1, 0.3, 0.5],  # 2개의 입력을 받는 3개의 뉴런 - 1층의 구조
               [0.2, 0.4, 0.6]    
])

B1 = np.array([0.1, 0.2, 0.3])  # 편향

In [25]:
X.shape, W1.shape, B1.shape

((2,), (2, 3), (3,))

In [26]:
# 계산 가능

In [27]:
# 활성화 함수에 들어갈 결과
z1 = np.dot(X, W1) + B1
z1

array([0.3, 0.7, 1.1])

In [28]:
# 신경망이 여러개 있는 것 : 딥러닝

In [29]:
def sigmoid(x):  # 활성화 함수 sigmoid
  return 1 / (1 + np.exp(-x))

In [30]:
# 활성화 함수까지 거친 3개의 결과
A1 = sigmoid(z1)
A1  # 브로드 캐스팅 일어남

array([0.57444252, 0.66818777, 0.75026011])

In [31]:
# 1층의 출력이 2층의 입력
# 2층의 구조
W2 = np.array([[0.1, 0.4],
               [0.2, 0.5],
               [0.3, 0.6]])  # 3개의 입력을 받는 2개의 뉴런
B2 = np.array([0.1, 0.2])

z2 = np.dot(A1, W2) + B2
A2 = sigmoid(z2)
A2

array([0.62624937, 0.7710107 ])

In [32]:
# 항등함수 : 신경망 회귀에서 많이 사용
def identity_function(x):
    return x

# 3층의 구조
W3 = np.array([[0.1, 0.3],
               [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

z3 = np.dot(A2, W3) + B3

# 출력층에 항등함수, softmax 많이 사용
y = identity_function(z3)
y

array([0.31682708, 0.69627909])